// @ts-nocheck

import { type ProductType } from '@/app/_types/product.type';

export const BANNER_PRODUCTS_2 = [
  {
    id: 1,
    imageUrl: 'https://i.ibb.co/V38Q3hg/Ad-Banner-01.jpg',
    alt: 'banner 1',
  },
  {
    id: 2,
    imageUrl: 'https://i.ibb.co/yW1f1kH/Ad-Banner-02.jpg',
    alt: 'banner 2',
  },
];

export const BANNER_PRODUCTS_3 = [
  {
    id: 1,
    imageUrl: 'https://i.ibb.co/w4Td53w/Ad-Banner-03.jpg',
    alt: 'banner 1',
  },
  {
    id: 2,
    imageUrl: 'https://i.ibb.co/3pFPQ0m/Ad-Banner-04.jpg',
    alt: 'banner 2',
  },
  {
    id: 3,
    imageUrl: 'https://i.ibb.co/h2DybXm/Ad-Banner-05.jpg',
    alt: 'banner 2',
  },
];

export const PRODUCTS_DATA: ProductType[] = [
  {
    id: '1',
    slug: 'abc',
    title: 'Shockproof Armor Case for iPhone',
    description: '',
    categories: [],
    price: {
      priceText: '$850',
      priceValue: 850,
      symbol: '$',
      currencyCode: 'USD',
    },
    originalPrice: 499,
    thumbnail: {
      url: 'https://i.ibb.co/wRBPcZz/cat9.png',
      altText: 'https://i.ibb.co/wRBPcZz/cat9.png',
      isPrimary: true,
      metaDescription: 'Shockproof Armor Case for iPhone',
      position: '',
      title: 'Shockproof Armor Case for iPhone',
    },
    rating: {
      number: 4,
      total: 4764,
    },
    offer: {
      timeLeft: 2299766814651,
      image: {
        url: 'https://i.ibb.co/bKP6232/img-event-bg.jpg',
        altText: 'bg',
        isPrimary: false,
        metaDescription: '',
        position: '',
        title: '',
      },
    },
    sellerId: '1',
    sellerSlug: 'abc',
    sellerStoreName: 'Senbowe Official Store',
  },
  {
    id: '2',
    slug: 'abc',
    title: 'Shockproof Armor Case for iPhone',
    description: '',
    categories: [],
    price: {
      priceText: '$850',
      priceValue: 850,
      symbol: '$',
      currencyCode: 'USD',
    },
    originalPrice: 499,
    totalSold: 1.2,
    thumbnail: {
      url: 'https://i.ibb.co/d6FSPFd/img-prod-01.jpg',
      altText: 'https://i.ibb.co/d6FSPFd/img-prod-01.jpg',
      isPrimary: true,
      metaDescription: 'Shockproof Armor Case for iPhone',
      position: '',
      title: 'Shockproof Armor Case for iPhone',
    },
    images: [
      {
        url: 'https://i.ibb.co/d6FSPFd/img-prod-01.jpg',
        altText: 'https://i.ibb.co/d6FSPFd/img-prod-01.jpg',
        isPrimary: true,
        metaDescription: 'Shockproof Armor Case for iPhone',
        position: '',
        title: 'Shockproof Armor Case for iPhone',
      },

      {
        url: 'https://i.ibb.co/d6FSPFd/img-prod-01.jpg',
        altText: 'https://i.ibb.co/d6FSPFd/img-prod-01.jpg',
        isPrimary: true,
        metaDescription: 'Shockproof Armor Case for iPhone',
        position: '',
        title: 'Shockproof Armor Case for iPhone',
      },

      {
        url: 'https://i.ibb.co/r20dbtb/img-product-detail-02.png',
        altText: 'https://i.ibb.co/r20dbtb/img-product-detail-02.png',
        isPrimary: true,
        metaDescription: 'Shockproof Armor Case for iPhone',
        position: '',
        title: 'Shockproof Armor Case for iPhone',
      },

      {
        url: 'https://i.ibb.co/HY3D2Wt/img-product-detail-03.png',
        altText: 'https://i.ibb.co/HY3D2Wt/img-product-detail-03.png',
        isPrimary: true,
        metaDescription: 'Shockproof Armor Case for iPhone',
        position: '',
        title: 'Shockproof Armor Case for iPhone',
      },

      {
        url: 'https://i.ibb.co/P4r8y3g/img-product-detail-04.png',
        altText: 'https://i.ibb.co/P4r8y3g/img-product-detail-04.png',
        isPrimary: true,
        metaDescription: 'Shockproof Armor Case for iPhone',
        position: '',
        title: 'Shockproof Armor Case for iPhone',
      },

      {
        url: 'https://i.ibb.co/nn0Q9wg/img-product-detail-05.png',
        altText: 'https://i.ibb.co/nn0Q9wg/img-product-detail-05.png',
        isPrimary: true,
        metaDescription: 'Shockproof Armor Case for iPhone',
        position: '',
        title: 'Shockproof Armor Case for iPhone',
      },

      {
        url: 'https://i.ibb.co/M5YZhYg/img-product-detail-06.png',
        altText: 'https://i.ibb.co/M5YZhYg/img-product-detail-06.png',
        isPrimary: true,
        metaDescription: 'Shockproof Armor Case for iPhone',
        position: '',
        title: 'Shockproof Armor Case for iPhone',
      },

      {
        url: 'https://i.ibb.co/K9wwz2k/img-product-detail-07.png',
        altText: 'https://i.ibb.co/K9wwz2k/img-product-detail-07.png',
        isPrimary: true,
        metaDescription: 'Shockproof Armor Case for iPhone',
        position: '',
        title: 'Shockproof Armor Case for iPhone',
      },
    ],
    sizes: [
      { label: 'XS', value: 'xs' },
      { label: 'S', value: 's' },
      { label: 'M', value: 'm' },
      { label: 'L', value: 'l' },
      { label: 'XL', value: 'xl' },
    ],
    colors: [
      { label: 'White', value: 'white', imageUrl: 'https://i.ibb.co/Y3Lvh0L/pdp-color-variant-1.png' },
      { label: 'Black', value: 'black', imageUrl: 'https://i.ibb.co/K2675Gt/pdp-color-variant-2.png' },
      { label: 'Silver', value: 'silver', imageUrl: 'https://i.ibb.co/MG39Q5K/pdp-color-variant-3.png' },
      { label: 'Blue', value: 'blue', imageUrl: 'https://i.ibb.co/2M2qXdX/pdp-color-variant-4.png' },
      { label: 'Green', value: 'green', imageUrl: 'https://i.ibb.co/rcK27F5/pdp-color-variant-5.png' },
    ],
    rating: {
      number: 4.5,
      total: 4764,
    },
    sellerId: '1',
    sellerSlug: 'abc',
    sellerStoreName: 'Senbowe Official Store',
  },
  {
    id: '3',
    slug: 'abc',
    title: 'Shockproof Armor Case for iPhone',
    description: '',
    categories: [],
    price: {
      priceText: '$850',
      priceValue: 850,
      symbol: '$',
      currencyCode: 'USD',
    },
    originalPrice: 499,
    thumbnail: {
      url: 'https://i.ibb.co/4Vh2n20/cat8.png',
      altText: 'https://i.ibb.co/4Vh2n20/cat8.png',
      isPrimary: true,
      metaDescription: 'Shockproof Armor Case for iPhone',
      position: '',
      title: 'Shockproof Armor Case for iPhone',
    },
    rating: {
      number: 4.2,
      total: 4764,
    },
    offer: {
      timeLeft: 2299766814651,
      image: {
        url: 'https://i.ibb.co/bKP6232/img-event-bg.jpg',
        altText: 'bg',
        isPrimary: false,
        metaDescription: '',
        position: '',
        title: '',
      },
    },
    sellerId: '1',
    sellerSlug: 'abc',
    sellerStoreName: 'Senbowe Official Store',
  },
  {
    id: '4',
    slug: 'abc',
    title: 'Shockproof Armor Case for iPhone',
    description: '',
    categories: [],
    price: {
      priceText: '$850',
      priceValue: 850,
      symbol: '$',
      currencyCode: 'USD',
    },
    originalPrice: 499,
    thumbnail: {
      url: 'https://i.ibb.co/wRBPcZz/cat9.png',
      altText: 'https://i.ibb.co/wRBPcZz/cat9.png',
      isPrimary: true,
      metaDescription: 'Shockproof Armor Case for iPhone',
      position: '',
      title: 'Shockproof Armor Case for iPhone',
    },
    rating: {
      number: 4,
      total: 4764,
    },
    sellerId: '1',
    sellerSlug: 'abc',
    sellerStoreName: 'Senbowe Official Store',
  },
  {
    id: '5',
    slug: 'abc',
    title: 'Shockproof Armor Case for iPhone',
    description: '',
    categories: [],
    price: {
      priceText: '$850',
      priceValue: 850,
      symbol: '$',
      currencyCode: 'USD',
    },
    originalPrice: 499,
    thumbnail: {
      url: 'https://i.ibb.co/wRBPcZz/cat9.png',
      altText: 'https://i.ibb.co/wRBPcZz/cat9.png',
      isPrimary: true,
      metaDescription: 'Shockproof Armor Case for iPhone',
      position: '',
      title: 'Shockproof Armor Case for iPhone',
    },
    rating: {
      number: 4,
      total: 4764,
    },
    sellerId: '1',
    sellerSlug: 'abc',
    sellerStoreName: 'Senbowe Official Store',
  },
  {
    id: '6',
    slug: 'abc',
    title: 'Shockproof Armor Case for iPhone',
    description: '',
    categories: [],
    price: {
      priceText: '$850',
      priceValue: 850,
      symbol: '$',
      currencyCode: 'USD',
    },
    originalPrice: 499,
    thumbnail: {
      url: 'https://i.ibb.co/wRBPcZz/cat9.png',
      altText: 'https://i.ibb.co/wRBPcZz/cat9.png',
      isPrimary: true,
      metaDescription: 'Shockproof Armor Case for iPhone',
      position: '',
      title: 'Shockproof Armor Case for iPhone',
    },
    rating: {
      number: 4,
      total: 4764,
    },
    sellerId: '1',
    sellerSlug: 'abc',
    sellerStoreName: 'Senbowe Official Store',
  },
  {
    id: '7',
    slug: 'abc',
    title: 'Shockproof Armor Case for iPhone',
    description: '',
    categories: [],
    price: {
      priceText: '$850',
      priceValue: 850,
      symbol: '$',
      currencyCode: 'USD',
    },
    originalPrice: 499,
    thumbnail: {
      url: 'https://i.ibb.co/wRBPcZz/cat9.png',
      altText: 'https://i.ibb.co/wRBPcZz/cat9.png',
      isPrimary: true,
      metaDescription: 'Shockproof Armor Case for iPhone',
      position: '',
      title: 'Shockproof Armor Case for iPhone',
    },
    rating: {
      number: 4,
      total: 4764,
    },
    sellerId: '1',
    sellerSlug: 'abc',
    sellerStoreName: 'Senbowe Official Store',
  },
  {
    id: '8',
    slug: 'abc',
    title: 'Shockproof Armor Case for iPhone',
    description: '',
    categories: [],
    price: {
      priceText: '$850',
      priceValue: 850,
      symbol: '$',
      currencyCode: 'USD',
    },
    originalPrice: 499,
    thumbnail: {
      url: 'https://i.ibb.co/wRBPcZz/cat9.png',
      altText: 'https://i.ibb.co/wRBPcZz/cat9.png',
      isPrimary: true,
      metaDescription: 'Shockproof Armor Case for iPhone',
      position: '',
      title: 'Shockproof Armor Case for iPhone',
    },
    rating: {
      number: 4,
      total: 4764,
    },
    sellerId: '1',
    sellerSlug: 'abc',
    sellerStoreName: 'Senbowe Official Store',
  },
  {
    id: '9',
    slug: 'abc',
    title: 'Shockproof Armor Case for iPhone',
    description: '',
    categories: [],
    price: {
      priceText: '$850',
      priceValue: 850,
      symbol: '$',
      currencyCode: 'USD',
    },
    originalPrice: 499,
    thumbnail: {
      url: 'https://i.ibb.co/wRBPcZz/cat9.png',
      altText: 'https://i.ibb.co/wRBPcZz/cat9.png',
      isPrimary: true,
      metaDescription: 'Shockproof Armor Case for iPhone',
      position: '',
      title: 'Shockproof Armor Case for iPhone',
    },
    rating: {
      number: 4,
      total: 4764,
    },
    sellerId: '1',
    sellerSlug: 'abc',
    sellerStoreName: 'Senbowe Official Store',
  },
  {
    id: '10',
    slug: 'abc',
    title: 'Shockproof Armor Case for iPhone',
    description: '',
    categories: [],
    price: {
      priceText: '$850',
      priceValue: 850,
      symbol: '$',
      currencyCode: 'USD',
    },
    originalPrice: 499,
    thumbnail: {
      url: 'https://i.ibb.co/wRBPcZz/cat9.png',
      altText: 'https://i.ibb.co/wRBPcZz/cat9.png',
      isPrimary: true,
      metaDescription: 'Shockproof Armor Case for iPhone',
      position: '',
      title: 'Shockproof Armor Case for iPhone',
    },
    rating: {
      number: 4,
      total: 4764,
    },
    sellerId: '1',
    sellerSlug: 'abc',
    sellerStoreName: 'Senbowe Official Store',
  },
  {
    id: '11',
    slug: 'abc',
    title: 'Shockproof Armor Case for iPhone',
    description: '',
    categories: [],
    price: {
      priceText: '$850',
      priceValue: 850,
      symbol: '$',
      currencyCode: 'USD',
    },
    originalPrice: 499,
    thumbnail: {
      url: 'https://i.ibb.co/wRBPcZz/cat9.png',
      altText: 'https://i.ibb.co/wRBPcZz/cat9.png',
      isPrimary: true,
      metaDescription: 'Shockproof Armor Case for iPhone',
      position: '',
      title: 'Shockproof Armor Case for iPhone',
    },
    rating: {
      number: 4,
      total: 4764,
    },
    sellerId: '1',
    sellerSlug: 'abc',
    sellerStoreName: 'Senbowe Official Store',
  },
  {
    id: '12',
    slug: 'abc',
    title: 'Shockproof Armor Case for iPhone',
    description: '',
    categories: [],
    price: {
      priceText: '$850',
      priceValue: 850,
      symbol: '$',
      currencyCode: 'USD',
    },
    originalPrice: 499,
    thumbnail: {
      url: 'https://i.ibb.co/wRBPcZz/cat9.png',
      altText: 'https://i.ibb.co/wRBPcZz/cat9.png',
      isPrimary: true,
      metaDescription: 'Shockproof Armor Case for iPhone',
      position: '',
      title: 'Shockproof Armor Case for iPhone',
    },
    rating: {
      number: 4,
      total: 4764,
    },
    sellerId: '1',
    sellerSlug: 'abc',
    sellerStoreName: 'Senbowe Official Store',
  },
];
